function [Theta_global] = doMLRRInference(cfg, data_counts_filtered, ...
    total_biomass, perturbations, T)

params = cfg.ridgeRegression;
mesh = logspace(params.min, params.max, params.N);

[F,time,ID,U,taxa_data,time_data,ID_data,U_data,F_prime,X, magnitude]=...
import_data_and_construct_matrices(data_counts_filtered, total_biomass, ...
    perturbations, T, params.normalize_counts, ...
    params.differentiation, params.scaling_factor, []);

[regularizer_global,Theta_global,Theta_mean]=...
    inf_regularization_based_inference(cfg.general.seed, F, time, ID, ...
    U, F_prime, X, mesh, params.k, ~(params.mix_trajectories), ...
    true, 'qp', true, [], params.replicates, magnitude);
%TODO: magnitude!

end